feat: add 'open in new tab' option
godaddy/wp-reseller-store pull request #153
Opened 2023-07-31 16:46 UTC by cbicuti-godaddy

RSV-1712 - New Tab Option for Cart and Domain

2023-07-31 19:21 UTC, cberesford-godaddy requested changes
Can you please add unit tests for this new functionality?
Something along the lines of "It should apply target=_blank when button_new_tab is checked"

2023-08-01 09:56 UTC, cburton-godaddy requested changes
+1 on tests too

2023-08-01 09:56 UTC, cburton-godaddy commented on .dev/src/blocks/product/components/inspector.js
> +					label={ __( 'Open in New Tab', 'reseller-store' ) }
**nitpick (non-blocking):** Casing does not match the other description for this.

`Display results in a new tab` vs `Open in New Tab`

Also latter misses the `a` too. Make these as consistent as possible whilst still making sense in context.

2023-08-01 09:56 UTC, cburton-godaddy commented on includes/modules/rstore-fl-product.php
> +							'label'   => __( 'Open in new tab', 'reseller-store' ),
**nitpick (non-blocking):** More inconsistency, casing is different to the other `Open in New Tab`

2023-08-01 09:56 UTC, cburton-godaddy commented on includes/modules/rstore-vc-product.php
> +						'heading'    => __( 'Open in new tab', 'reseller-store' ),
**nitpick (non-blocking):** Make consistent

2023-08-01 09:56 UTC, cburton-godaddy commented on includes/widgets/class-product.php
> +				$content .= rstore_add_to_cart_form( $post_id, false, $data['button_label'] . 'a', $data['button_new_tab'], $data['text_cart'], $data['redirect'] );
**question (non-blocking):** What's the `. 'a'` for here?

2023-08-01 14:13 UTC, cburton-godaddy approved these changes

2023-08-03 10:33 UTC, merged